# Generated by Django 4.0.6 on 2022-07-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiappRojzePatricio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=45)),
                ('Provincia', models.CharField(max_length=30)),
                ('NroAmbientes', models.IntegerField()),
            ],
        ),
    ]
