# Generated by Django 4.0.6 on 2022-07-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiappRojzePatricio', '0002_domicilios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=35)),
                ('Apellido', models.CharField(max_length=35)),
                ('Edad', models.IntegerField()),
                ('FechaNacimiento', models.DateTimeField()),
            ],
        ),
    ]
